version: '3.8'

services:
  simple-queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-queue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    networks:
      - queue-network

networks:
  queue-network:
    driver: bridge